pages:
  stage: deploy
  image: julia:1
  script:
    - cd generate
    - cp generate.jl generate2.jl
    - julia -e '
          import Pkg;
          Pkg.add("Pluto"); import Pluto;
          Pluto.activate_notebook_environment("generate2.jl");
          Pkg.instantiate();
          include("generate.jl")'
    - cd ..
    - mv ./website/__site public
  artifacts:
    paths:
      - public
  rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  cache:
    paths:
      - pluto_state_cache

